import Layout from "./components/base-app/layout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-slate-50 to-indigo-50">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
